name: "Borg-based Backup for Home Assistant"
version: "2.0.0"
slug: "borg_backup"
description: "Add-on providing access to Borg in automations. So, you can easily create compressed deduplicated remote backups"
url: "https://github.com/ceskyDJ/home-assistant-borg-backup/"
image: "ghcr.io/ceskydj/{arch}-borg-backup"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: "services"
boot: "manual"
hassio_role: "backup"
hassio_api: true
homeassistant_api: true
map:
  - addon_config:rw
  - backup:rw
options:
  borg_backup_debug: false
schema:
  borg_user: "str"
  borg_host: "str"
  borg_repo_name: "str"
  borg_passphrase: "str"
  borg_ssh_params: "str?"
  borg_compression: "str?"
  borg_backup_debug: "bool"
